### PR TITLE
Single constant propagation

### PR DESCRIPTION
**Pull request by CraigA-ZA**
Single constant propagation

### CODE REVIEW

**Review by Zhunaidm — CHANGES_REQUESTED** [review]
So this does a simplification once over and does not yet allow for multiple simplifications yet? Also please try to be consistent with your style when when making a pull request.

**Comment by craigils** [comment]
I have implemented basic constant propagation. It does not yet look ahead though.
I have made quite a few changes since the original pull request. I'm not really sure how this works.. Hopefully you can see the changes here.

**Review by Zhunaidm — COMMENTED** [review]
Cool looks a lot better! The build seems to be failing. I suggest only include test cases that your basic simplification can do.

**Comment by CraigA-ZA** [comment]
Yeah, it’s failing the more complicated tests. But since the Dockerfile clones the most recent copy of the program, there doesn’t seem to be a way to only make it run the basic tests. Unless I push only the simple tests and then wait until you review it.
Or should I be making another branch to work on step 2 (simplification)

**Comment by Zhunaidm** [comment]
So in normal circumstances you would merge your branch with the tests that test the specific functionality you have added, in this case it's just single constant simplification. The build should then pass and then once it's merged you would continue to work on your branch and merge once the next step is complete.

So it's an iterative process in tune with that agile is.

**Comment by CraigA-ZA** [comment]
Ah okay cool, I understand.
I've changed the tests to the one that my feature can do.

**Comment by Zhunaidm** [comment]
Cool! The pull request would be approved at this point. Well done.

**Comment by CraigA-ZA** [comment]
As discussed last week, I merged my first feature to the master branch and continued working on the dev branch, but I have ended up not being able to create another pull request now (Presuming I was supposed to).
I wanted to make another pull request to say that I have now done constant propagation and simplification. I'd like to believe that all that is missing is "Handling of transitive propagation up to a fixed point". I just do a single iteration of propagation and then simplification.

**Pull request closed without merging**
